const MARQUEE_TEXT =
  "ARTIFICIAL INTELLIGENCE SYSTEMS · DISTRIBUTED ARCHITECTURE · LLM ORCHESTRATION · MACHINE LEARNING INFRASTRUCTURE · SCALABLE SOFTWARE SYSTEMS · SYSTEMS ENGINEERING · APPLIED MACHINE INTELLIGENCE · DATA INFRASTRUCTURE · MODEL DEPLOYMENT ARCHITECTURE · HIGH-PERFORMANCE BACKENDS · COMPUTATIONAL SYSTEMS · AUTONOMOUS AGENT DESIGN · INFERENCE PIPELINES · RESILIENT CLOUD ARCHITECTURE · PRODUCTION-GRADE ML · AI PLATFORM ENGINEERING · EVENT-DRIVEN SYSTEMS · STATEFUL SERVICES · MODEL LIFECYCLE MANAGEMENT · ENTERPRISE ARCHITECTURE · INTELLIGENT INFRASTRUCTURE · KNOWLEDGE SYSTEMS · PARALLEL COMPUTATION · SECURE API ARCHITECTURE · SCALABLE DISTRIBUTED SERVICES · ALGORITHMIC SYSTEM DESIGN · LARGE-SCALE DATA PROCESSING · REAL-TIME INFERENCE · CLOUD-NATIVE SYSTEMS · FAULT-TOLERANT ARCHITECTURE · PRODUCTION AI SYSTEMS · COMPUTE OPTIMIZATION · BACKEND SYSTEM DESIGN · LLM INTEGRATION · ENTERPRISE-SCALE DEPLOYMENTS · ";

const Marquee = () => {
  return (
    <div className="fixed bottom-0 left-0 right-0 z-50 overflow-hidden py-3 bg-background">
      <div className="animate-marquee whitespace-nowrap flex">
        <span className="font-display text-sm tracking-[0.3em] text-foreground opacity-50 mr-4">
          {MARQUEE_TEXT}
        </span>
        <span className="font-display text-sm tracking-[0.3em] text-foreground opacity-50 mr-4">
          {MARQUEE_TEXT}
        </span>
      </div>
    </div>
  );
};

export default Marquee;
